apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eso-demo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstoredemo
    kind: SecretStore
  target:
    name: eso-demo
    creationPolicy: Owner
  data:
  - secretKey: db-username
    remoteRef:
      key: prod/godemo/db
      property: username
  - secretKey: db-password
    remoteRef:
      key: prod/godemo/db
      property: password